# Railway Configuration for Workie.lk Backend
# This file tells Railway to deploy the backend folder

[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NODE_VERSION = "18"
