# Nixpacks Configuration for Backend Directory
# This is used when Railway detects package.json in backend/

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --production=false"]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
